### ISSUE TITLE
Each request get two times response here

### ISSUE THREAD

**Issue by javinjiao** [1iveowl/SimpleHttpListener.Rx#12]
https://github.com/1iveowl/SimpleHttpListener.Rx/blob/11fa09fb8446480ea470e782221b3392824e359e/src/test/HttpListener.Rx.Test/Program.cs#L117

I just start the test program and send the address on chrome browser one time,the output window log twice like this:
Press any key to stop.
Remote Address: 127.0.0.1
Remote Port: 64786
Local Address: 127.0.0.1
Local Port: 1901
--------------***-------------
Remote Address: 127.0.0.1
Remote Port: 64787
Local Address: 127.0.0.1
Local Port: 1901
--------------***-------------

**Comment by 1iveowl** [comment]
Thank you.

It's now an issue with the library. It's an issue with Chrome. 

I was able to reproduce with Chrome. Sure enough, two requests are send. However, if I try this from Postman, only one request is send.

Others have notices this behavior from Chrome. Apparently it's by design. From Stack Overflow: [What to do with chrome sending extra requests?](https://stackoverflow.com/questions/4460661/what-to-do-with-chrome-sending-extra-requests)

**Comment by 1iveowl** [comment]
@javinjiao can you confirm that you agree that this issue is closed please?
